<?xml version="1.0" encoding="utf-8"?><Database Name="Workers" Class="DatabaseWorkersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Marcin\OneDrive\StudiaOneDrive\4.Programowanie_komponentowe\bazy\Workers.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DatabaseWorkers.Properties.Settings" SettingsPropertyName="WorkersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Worker" Member="Workers">
    <Type Name="Worker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateBegin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Manager" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>