<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseIcons" Class="DatabaseIconsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DatabaseIcons.mdf;Integrated Security=True" SettingsObjectName="_088_EditorIcons.Properties.Settings" SettingsPropertyName="DatabaseIconsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Icon" Member="Icons">
    <Type Name="Icon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Icon_IconPoint" Member="IconPoints" ThisKey="Id" OtherKey="IconId" Type="IconPoint" />
    </Type>
  </Table>
  <Table Name="dbo.IconPoint" Member="IconPoints">
    <Type Name="IconPoint">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IconId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Icon_IconPoint" Member="Icon" ThisKey="IconId" OtherKey="Id" Type="Icon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>